config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root to: 'public#index'
  get '/contact' , to: 'public#contact'
  get '/team' , to: 'public#team'
  get '/welcome' , to: 'public#welcome'
  
  
  # get '/gossips', to: 'gossips#index'
  # get '/gossips/:id' ,to: 'gossips#show' , as: 'gossip'

  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]


  resources :users do
    resources :gossips
  end
  # get '/user'  , to: 'user#show', as: 'user'


  # get 'New%gossip' , to: 'gossip#newgossip'
  # get '/patients'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :likes, through: :gossips
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,  uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "entrez une addresse valide" }
  validates :age, presence: true,  numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @gossips = @user.gossips
    @city = City.find(@user.city_id).name
  

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      age: params[:age],
      description: params[:description],
      city_id: params[:city],
      password: params[:password]
    )
    if @user.save
      log_in(@user)
      flash[:success] = "Utilisateur bien créé"
      redirect_to user_path(@user) 
    else
      flash[:alert] = "Utilisateur non créé"
      redirect_to '/'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Utilisateur mis à jour"
      redirect_to show_user_path(@user) 
    else
      flash[:alert] = "Mise à jour de l'utilisateur échouée"
      redirect_to edit_user_path(@user) 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to root_path
  end

  def like?(gossip)
    likes.exists?(gossip: gossip)
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :description, :city, :password , :age)
  end
end  

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
  </style>
</head>
<body>

<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><a href="/users/id">Mon Compte</a></p>
        <%= image_tag("martin mystere.png", alt: "avatar", class: "img-circle", style: "width: 150px;") %>
      </div>
      <div class="well">
        <p><a href="#">Mes tags</a></p>
        <p>
          <span class="label label-default">News</span>
          <span class="label label-primary">gossips</span>
          <span class="label label-success">bitch</span>
          <span class="label label-info">party</span>
          <span class="label label-warning">Gaming</span>
          <span class="label label-danger">Friends</span>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Ey!</strong></p>
        People are looking at your profile. Find out who.
      </div>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling comme une princesse d'upper east side</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>     
            </div>
          </div>
        </div>
      </div>
      
    <% @users.each do |user| %>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
            <p><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %> <br>(ID: <%= user.id %>)</p>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <% if user.gossips.any? %>
              <p><%= link_to user.gossips.sample.title, user_gossip_path(user, user.gossips.sample) %></p>
            <% else %>
              <p>Aucun gossips</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/users/new.html.erb
<div class="container">
    <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p >We failed to create the gossip for the following reason(s) :</p>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Devenir un Gossipeur</h1>
  <div>
    <%= form_tag url_for(action: 'create'), method: "post" do %>
        <div><%= label_tag 'Quel est ton prénom ?' %></div>
        <div><%= text_field_tag 'first_name', @user.first_name, class: "form-control" ,required: true %><br></div>

        <div><%= label_tag 'Quel est ton nom ?' %></div>
        <div><%= text_field_tag 'last_name', @user.last_name, class: "form-control" ,required: true %><br></div>

        <div><%= label_tag 'Quel est ton âge ?' %></div>
        <div><%= text_field_tag 'age', @user.age, class: "form-control" ,required: true %><br></div>

        <div><%= label_tag 'Quelle est ta ville ? :' %></div>
        <div><%= select_tag 'city', options_from_collection_for_select(City.all, "id", "name",@user.city) , class: "form-control" %><br></div>

        <div><%= label_tag 'Décris-toi en quelques mots :' %></div>
        <div><%= text_area_tag 'description', @user.description, class: "form-control"  %><br></div>

        <div><%= label_tag 'Donne-nous un email :' %></div>
        <div><%= text_field_tag 'email', @user.email, class: "form-control",required: true %><br></div>

        <div><%= label_tag 'Choisis ton mot de passe :' %></div>
        <div><%= password_field_tag 'password', @user.password, class: "form-control",required: true %><br>
          <div class="invalid-feedback">
            Please enter a valid password (at least 6 characters).
          </div>
        </div>
        <%= submit_tag "Valider", class: "btn btn-secondary m-1"%>       
    <% end %>
    <br> 
  </div>
</div>

app/views/users/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/users">Gossipeurs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Mon Profile</li>
          </ol>
        </nav>
      </div>
    </div>
  

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
          <%= image_tag("martin mystere.png", alt: "avatar", class: "rounded-circle img-fluid", style: "width: 150px;") %>

            <h5 class="my-3"><%= @user.first_name %> <%= @user.last_name %></h5>
            <p class="text-muted mb-1">ID: <%= @user.id %></p>
            <p class="text-muted mb-4"><%= @user.city.name %> (<%= @user.city.zip_code %>)</p>
            <div class="d-flex justify-content-center mb-2">
              <button type="button" class="btn btn-primary">Follow</button>
              <button type="button" class="btn btn-outline-primary ms-1">Envoyer un message</button>
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fas fa-globe fa-lg text-warning"></i>
                <p class="mb-0">Pornhub</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">Martin.mymy</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                <p class="mb-0">@El_Mysterio</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                <p class="mb-0">CallMeMystery</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                <p class="mb-0">Martin Mystere</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name %> <%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"> <%= @user.email %></p></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Age</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.age %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Nombre de gossips</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.gossips.count%></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.city.name %> (<%= @user.city.zip_code %>)</p>
              </div>
            </div>
          </div>
        </div>

        <%# ----------------------------------------------- %>
      <div class="row m-2 ">
        <div class="card mb-4 mb-md-0">
            <div class="card-body">
              <h2>Gossips écrits par <%= @user.first_name %></h2>
              <ul>
                <% @gossips.each do |gossip| %>
                  <li>
                    <%= link_to gossip.title, gossip_path(gossip) %> (ID: <%= gossip.id %>)
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          <%# ------------------------------------------------------ %>

            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4">
                  <span class="text-primary font-italic me-1">RANG : </span><em>Langue de vipère</em>
                </p>
                <p class="mb-1" style="font-size: .77rem;">Nombre de gossips</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Hot Scoop</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Influence</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Bitching</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Stalking</p>
                <div class="progress rounded mb-2" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
<%# ------------------------------------------------------ %>
        </div>
      </div>
    </div>
  </div>
</section>