config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root to: 'public#index'
  get '/contact' , to: 'public#contact'
  get '/team' , to: 'public#team'
  get '/welcome' , to: 'public#welcome'
  
  
  # get '/gossips', to: 'gossips#index'
  # get '/gossips/:id' ,to: 'gossips#show' , as: 'gossip'

  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]


  resources :users do
    resources :gossips
  end
  # get '/user'  , to: 'user#show', as: 'user'


  # get 'New%gossip' , to: 'gossip#newgossip'
  # get '/patients'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :likes , through: :users
  has_many :tags, through: :inter_tag_gossips
  validates :content, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 140 }
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def show
    @gossip = Gossip.find(params[:id])
  end

  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(content: params[:content], title: params[:title], user_id: User.all.sample.id)
    @gossip.user = current_user
    if @gossip.save
      flash[:success] = "Xoxo Gossip saved successfully"
      redirect_to "/"
    else
      flash[:alert] = "Veuillez vous connecter chef"
      redirect_to "/"
    end 
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    gossip_params = params.require(:gossip).permit(:title, :content)
    @gossip = Gossip.find_by(id: params[:id])
    @gossip.update(gossip_params)

  end

  def destroy
    @gossip = Gossip.find_by(id: params[:id])
    @gossip.destroy
    flash[:success] = "Ouppsss Gossip supprimé "
    redirect_to "/"
  end

  def like
    @gossip = Gossip.find(params[:id])
    current_user.like.create(gossip: params[:gossip])
    redirect_to gossips_path, notice: "oh u like it hun"
  end

  def unlike
    @gossip = Gossip.find(params[:id])
    current_user.Like.find(gossip: params[:gossip]).destroy
    redirect_to gossips_path, notice: "Ah finalement non ?"
  end

  private
  def gossip_params 
    gossip_params = params.require(:gossip).permit(:title, :content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
  def authenticate_author
    @gossip = Gossip.find(params[:id])
    unless @gossip.user == current_user
      flash[:danger] = "You are not allowed to edit this gossip."
      redirect_to gossips_path
    end
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<style>
  .items-align-center {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh; /* Optionally, you can set a minimum height to center vertically. */
  }
  .titre{
    font-size:3em;
    font-family: Copperplate, Papyrus, fantasy;
    
  }
</style>



<div class="items-align-center" >
  <h1 class="titre" >Modifier un gossip</h1>
  <div class="container m-5" >
    <%= form_for @gossip do |f| %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header bg-dark text-white"><h4>Modifie ton potin<h4> </div>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <h4><label for="name">Titre</label><h4>
                  <div class="field">
                    <%= f.text_field :title, class: 'form-control', placeholder: 'Entre 3 et 24 caractères', required: true %>
                  </div>  
                </div>
                <div class="form-group">
                  <h4><label for="message">Potin</label><h4>
                  <div class="field">
                    <%= f.text_area :content, class: 'form-control', rows: 6, required: true  %>
                  </div>                                 
                <div class="mx-auto">
                  <%= f.submit "Sauvegarder la modification", class: "btn btn-dark m-2" %>
                </div>
                </div>
              </form>
            </div>
          </div>
        </div>    
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/gossip.html.erb
<div class="jumbotron p-3 p-md-5 text-white bg-dark text-center">
 <div class="d-flex justify-content-center align-items-center">
    <h1 class="display-4">Gossip n°<%= params[:id] %></h1>
<!-- Votre contenu jumbotron ici -->
 </div>
</div>

        <div class="d-flex justify-content-center">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic"><%= @gossip.title %></h1>
    <h2 class="display-4 font-italic"> Auteur : <%= @gossip.user.first_name %> </h2>
    <p class="lead my-3">
      <%= @gossip.content %><br>
      Crée le : <%= @gossip.created_at %>
    </p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
        <div class="card m-3">
          <div class="card-body">
            <h5 class="card-title">Gossip n°<%= gossip.id %></h5>
            <h6 class="card-subtitle mb-2 text-muted">Par <%= gossip.user.first_name %></h6>
            <p class="card-text"><%= gossip.title %></p>

            <%= button_to "Voir plus", gossip_path(gossip.id), method: :get, class: "btn btn-outline-primary btn-sm m-1" %>
            <%= button_to "Voir l'auteur", user_path(gossip.user.id), method: :get, class: "btn btn-outline-warning btn-sm m-1" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<style>
  .items-align-center {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh; /* Optionally, you can set a minimum height to center vertically. */
  }
  .titre{
    font-size:3em;
    font-family: Copperplate, Papyrus, fantasy;
    
  }
</style>


<div class="items-align-center" >
  <h1 class="titre" >Créer un nouveau gossip</h1>
  <div class="container m-5" >
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header bg-dark text-white"><i class="fa fa-envelope"></i> balance to potin </div>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <label for="name">Titre</label>
                  <div>
                    <%= text_field_tag 'title', @gossip.title, class: 'form-control', placeholder: 'Entre 3 et 24 caractères', required: true %> 
                  </div>      
                </div>
                <div class="form-group">
                  <label for="message">Potin</label>
                  <div>
                    <%= text_area_tag 'content', @gossip.content, class: 'form-control', rows: 6, required: true %>
                  </div>
                </div>
                <div class="mx-auto">
                  <%= submit_tag "C'est parti...", class: "btn btn-dark m-2"%>
                </div>
              </form>
            </div>
          </div>
        </div>    
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/show.html.erb
<div class="jumbotron p-3 p-md-5 text-white bg-dark text-center">
  <div class="d-flex justify-content-center align-items-center">
    <h1 class="display-4">Gossip n°<%= params[:id] %></h1>
    <!-- Votre contenu jumbotron ici -->
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic"><%= @gossip.title %></h1>
    <h2 class="display-4 font-italic"> Auteur : <%= @gossip.user.first_name %> </h2>
    <p class="lead my-3">
      <%= @gossip.content %><br>
      Crée le : <%= @gossip.created_at.strftime("%d/%m/%Y à %H:%M") %> a    <%= link_to @gossip.user.city.name, city_path(@gossip.user.city_id) %>
    </p>
    <% if logged_in? == true && current_user == @gossip.user %>
      <% if current_user.likes.include?(@gossip) %>
        <%= button_to "Ne plus aimer", gossip_path(@gossip.id), method: :delete, class: "btn btn-danger mb-2" %>
      <% else %>
        <%= button_to "Aimer", gossip_path(@gossip.id), method: :post , class: "btn btn-success mb-2" %>
      <% end %>
      <%= link_to "Modifier", edit_gossip_path(@gossip), class: "btn btn-info m-1" %>
      <%= button_to "Supprimer le gossip", gossip_path(@gossip), data: { confirm: "Etes vous sur?"}, method: :delete, class: "btn btn-danger m-1" %>
    <% end %>
  </div>
</div>